# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_gcatcirc_wrappers", use_symbols = TRUE, package_name = "gcatcirc")

#' @docType package
#' @usage NULL
#' @useDynLib gcatcirc, .registration = TRUE
NULL

#' If a set of words is not a code it returns all ambiguous sequences.
#'
#' This function returns all ambiguous sequences
#' which only exist if a set of words \emph{X} is by
#' definition not a code. Such a sequence can be decomposed in
#' at least two disjoint sets of words of \emph{X}.
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return A String vector with all ambiguous sequences.
#'
#' @seealso \link{is_code}
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' all_ambiguous_sequences(code)
#'
#' @export
all_ambiguous_sequences <- function(tuples) .Call(wrap__all_ambiguous_sequences, tuples)

#' Checks whether the set of words is a code or not
#'
#' This function returns true if a set of words is by
#' definition a code. A code \emph{X} is a set of words so that
#' any sequence has at most one decomposition in words of \emph{X}
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return A Boolean. If true the code is a code
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' is_code(code)
#'
#' @export
is_code <- function(tuples) .Call(wrap__is_code, tuples)

#' Shifts each tuple by `sh` positions
#'
#' Under the concept shift is understood a circular permutation, i.e.
#' let \emph{X}={123, 332}, then c.shift(2) results in {312, 233}
#'
#' @param tuples A gcatbase::gcat.code object
#' @param sh A integer, the shift index, i.e. the number of shifts.
#'
#' @return Boolean value. True if the code is circular.
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' circular_shift(code, 2)
#'
#' @export
circular_shift <- function(tuples, sh) .Call(wrap__circular_shift, tuples, sh)

#' Check if a code is circular.
#'
#' This function checks if a code is circular. Circular codes are sets of
#' tuples \emph{X} of different tuple length where
#' every concatenation of words \emph{w} in \emph{X} written on a circle
#' has only a single decomposition into words from \emph{X}.\cr
#' For more info on this subject read:\cr
#' \link{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5492142/},\cr
#' \link{http://dpt-info.u-strasbg.fr/~c.michel/Circular_Codes.pdf},\cr
#' \emph{2007 Christian MICHEL. CIRCULAR CODES IN GENES}
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return Boolean value. True if the code is circular.
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' is_code_circular(code)
#'
#' @export
is_code_circular <- function(tuples) .Call(wrap__is_code_circular, tuples)

#' Check if a code is comma free.
#'
#' This function checks if a code is comma free.
#' Comma free codes are a more restrictive codes from the circular code family.
#' A comma free code \emph{X} is a code in which no concatenation of a
#' nonempty suffix of any word from \emph{X} and a nonempty prefix of any word from \emph{X} forms a word from \emph{X}.\cr
#' This is an extended property of the circular codes. See \link{is_code_circular} for more details.\cr
#' For more info on this subject read:\cr
#' \link{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5492142/},\cr
#' \link{http://dpt-info.u-strasbg.fr/~c.michel/Circular_Codes.pdf},\cr
#' \emph{2007 Christian MICHEL. CIRCULAR CODES IN GENES}
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return Boolean value. True if the code is comma free.
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' is_code_comma_free(code)
#'
#' @seealso \link{is_code_circular}
#'
#' @export
is_code_comma_free <- function(tuples) .Call(wrap__is_code_comma_free, tuples)

#' Check if a code is strong comma free.
#'
#' This function checks if a code is strong comma free.
#' Strong comma free codes are a more restrictive codes from the circular code family.
#' A strong comma free code \emph{X} is a code in which no nonempty suffix of any word from \emph{X}
#' is a nonempty prefix of any word from \emph{X}.\cr
#' This is an extended property of the circular codes. See \link{is_code_comma_free} for more details.\cr
#' For more info on this subject read:\cr
#' \link{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5492142/},\cr
#' \link{http://dpt-info.u-strasbg.fr/~c.michel/Circular_Codes.pdf},\cr
#' \emph{2007 Christian MICHEL. CIRCULAR CODES IN GENES}
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return Boolean value. True if the code is strong comma free.
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' is_code_strong_comma_free(code)
#'
#' @seealso \link{is_code_circular}, \link{is_code_comma_free}
#'
#' @export
is_code_strong_comma_free <- function(tuples) .Call(wrap__is_code_strong_comma_free, tuples)

#' This function checks if a code is Cn-circular.
#'
#' A code is cn circular if all circular permutations of the code (of all tuples) are circular codes again.
#' In total, this function checks 'x' circular permutations where 'x' is the least
#' common multiple of all tuple lengths used. This is an extended property of circular codes.
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return Boolean value. True if the code is Cn circular.
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' k <- is_code_cn_circular(code)
#'
#' @seealso \link{is_code_circular}
#'
#' @export
is_code_cn_circular <- function(tuples) .Call(wrap__is_code_cn_circular, tuples)

#' This function checks if a code is k-circular.
#'
#' K circle codes are a less restrictive code from the family of circle codes. These codes only ensure that for every
#' concatenation of less than k tuples from \emph{X} written on a circle, there is only one partition in tuples from \emph{X}.\cr
#' For mor details see: \link{https://link.springer.com/article/10.1007/s11538-020-00770-7}
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return Integer value, the exact k value of the k-circularity.
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' k <- get_exact_k_circular(code)
#'
#' @seealso \link{is_code_circular}
#'
#' @export
get_exact_k_circular <- function(tuples) .Call(wrap__get_exact_k_circular, tuples)

#' This function checks if a code is K-Graph circular.
#'
#' K-graph circle codes are a more restrictive than k-circle codes.
#' These codes only ensure that all cycles in the representing graph have a common length.
#' If the code is circular or the code contains cycles of
#' different length the teh function returns -1. \cr
#' For mor details see: \link{https://link.springer.com/article/10.1007/s11538-020-00770-7}
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return Integer value, the k-graph value of the k-graph-circularity. If code is not k-graph circle it returns -1.
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' k <- get_k_graph_circular(code)
#'
#' @seealso \link{get_exact_k_circular}
#'
#' @export
get_k_graph_circular <- function(tuples) .Call(wrap__get_k_graph_circular, tuples)

#' Returns the graph associated to a code
#'
#' @param tuples a gcatbase::gcat.code object
#' @param show_cycles a boolean, if true all edges in all cyclic paths a red
#' @param show_longest_path a boolean, if true all edges in all longest paths a red
#'
#' @return a rust graph-object associated to a code
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' g <- get_representing_graph_obj(code,2)
#'
get_representing_graph_obj <- function(tuples, show_cycles, show_longest_path) .Call(wrap__get_representing_graph_obj, tuples, show_cycles, show_longest_path)

#' Returns a i-component associated to a code
#'
#' @param tuples a gcatbase::gcat.code object
#' @param i a integer the component index
#' @param show_cycles a boolean, if true all edges in all cyclic paths a red
#' @param show_longest_path a boolean, if true all edges in all longest paths a red
#'
#' @return a i-component rust graph-object associated to a code
#'
#' @examples
#' code <- gcatbase::code(c("ACGC", "CGGG", "AC"))
#' g <- get_representing_component_obj(code,2)
#'
get_representing_component_obj <- function(tuples, i, show_cycles, show_longest_path) .Call(wrap__get_representing_component_obj, tuples, i, show_cycles, show_longest_path)

#' Returns a list of all longest paths
#'
#' This function returns all longest paths
#' in the graph associated to a set of words \emph{X}.
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return A list of String vectors with all longest paths.
#'
#' @seealso \link{get_representing_graph}
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGG", "AC"))
#' lp <- get_longest_paths(code)
#'
#' @export
get_longest_paths <- function(tuples) .Call(wrap__get_longest_paths, tuples)

#' Returns a list of all cyclic paths
#'
#' This function returns all cyclic paths
#' in the graph associated to a set of words \emph{X}.
#'
#' @param tuples A gcatbase::gcat.code object
#'
#' @return A list of String vectors with all cyclic paths
#'
#' @seealso \link{get_representing_graph}
#'
#' @examples
#' code <- gcatbase::code(c("ACG", "CGA", "CA"))
#' lp <- get_cyclic_paths(code)
#'
#' @export
get_cyclic_paths <- function(tuples) .Call(wrap__get_cyclic_paths, tuples)

